name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v7.0.1
      - name: 使用 pnpm
        uses: pnpm/action-setup@v6.0.10
        with:
          version: 10.34.4
      - name: 安装node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 类型检查
        run: pnpm type-check
      - name: 打包
        run: pnpm build:test
      - name: 部署到gh-pages分支
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
